# LAMMPS on HPC Jekyll configuration
---
#------------------------------------------------------------
# SITE specific configuration
#------------------------------------------------------------
# Cluster host and scheduler options: the defaults come from
# SuperMUC-NG, running SLURM. Other options can
# be found in the library of snippets_library,
# `_includes/snippets_library`. To use one, replace options
# below with those in `_config_options.yml` from the
# library. E.g, to customise for Cirrus at EPCC, running
# PBS, we could replace the options below with those from
#
# _includes/snippets_library/EPCC_Cirrus_pbs/_config_options.yml
#
# If your cluster is not represented in the library, please
# copy an existing folder, rename it, and customize for your
# installation. Remember to keep the leading slash on the
# `snippets` variable below!
snippets: "/snippets_library/SLURM-SuperMUC-NG"
local:
  prompt: "[user@laptop ~]$"

remote:
  name: "SuperMUC-NG"
  login: "" # EDIT ME 
  host: "" # EDIT ME
  node: "" # EDIT ME
  location: "Leibniz Supercomputing Centre"
  homedir: "" # EDIT ME
  prompt: "" # EDITME

sched:
  name: "SLURM"
  user: "yourUsername"
  submit:
    name: "sbatch"
    # Use this to include account options etc. when submitting
    options: ""
  status: "squeue"
  flag:
    user: "-u yourUsername"
    interactive: "--pty /bin/bash -i"
    histdetail: "-l -j"
    account: "--account"
    export: "--export=NONE"
    env: "--get-user-env"
    name: "-J"
    output: "-o"
    error: "-e"
    directory: "-D"
    time: "--time"
    queue: "--partition"
    node: "--nodes"
    tasks_node: "--ntasks-per-node"
  del: "scancel"
  interactive: "mpiexec"
  info: "sinfo"
  comment: "#SBATCH"
  ntasks: "$SLURM_NTASKS"
  hist: "sacct -u yourUsername"
  queue:
    default: "batch"

hemelb:
  env: 
    - "module purge \n"
    - "module load slurm_setup \n"
    - "module load intel/19.0.5 \n"
    - "module load intel-mpi/2019-intel"
  exec: "/dss/dsshome1/00/di39tav2/codes/HemePure/src/build_PP/hemepure" # CORRECT???


mpi_runtime:
  implementation: "ParaStation"
  launcher: "mpiexec"

# Interactive queue names, one or more as a list
workshop_interactive_queues:
  - devel
  - develgpus

#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this?
# "swc": Software Carpentry
# "dc":  Data Carpentry
# "lc":  Library Carpentry
# "cp":  Carpentries (e.g., instructor training)
carpentry: "swc"

# Overall title for pages.
title: "Running HemeLB on HPC systems"

# Email address, no mailto:
email: "j.mccullough@ucl.ac.uk"

# Life cycle stage of the lesson
# possible values: "pre-alpha", "alpha", "beta", "stable"
life_cycle: "alpha"

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "lesson"

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Magic to make URLs resolve both locally and on GitHub. Please don't change.
repository: <USERNAME>/<PROJECT>

# Invoke the Carpentries theme rather than copying into our repository.
remote_theme: carpentries/carpentries-theme

# Sites.
amy_site: "https://amy.carpentries.org/"
carpentries_github: "https://github.com/carpentries"
carpentries_pages: "https://carpentries.github.io"
carpentries_site: "https://carpentries.org/"
dc_site: "https://datacarpentry.org"
example_repo: "https://github.com/carpentries/lesson-example"
example_site: "https://carpentries.github.io/lesson-example"
lc_site: "https://librarycarpentry.org/"
swc_github: "https://github.com/swcarpentry"
swc_pages: "https://swcarpentry.github.io"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/carpentries/styles"
training_site: "https://carpentries.github.io/instructor-training"
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"
cc_by_human: "https://creativecommons.org/licenses/by/4.0/"

# Specify that things in the Episodes and Extras collections should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html
# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page
# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
  - .vendor/
  - .docker-vendor/
# Turn on built-in syntax highlighting.

highlighter: rouge

theme: jekyll-theme-cayman
