# LRZ, Leibniz Supercomputing Centre: Jureca + SBATCH
host_name: "SuperMUC-NG"
host_login: "" # EDIT ME
host_location: "Leibniz Supercomputing Centre"
host_homedir: ""  # EDIT ME
host_prompt: "[user@laptop ~]$"
sched_name: "SBATCH" # Check
sched_submit: "sbatch"
sched_submit_options: "-A course01" # EDITME
sched_flag_time: "--time "
sched_flag_node: "--nodes "
sched_status: "sstat"
sched_flag_user: "-u yourUsername"
sched_del: "scancel"
sched_interactive: "sbatch"
sched_comment: "#SBATCH"
sched_flag_name: "-N" # EDITME
sched_hist: "" # EDITME
sched_flag_histdetail: "" # EDITME 
module_options: "" #EDITME
run_openmp: "srun"
run_mpi: ""


